### ISSUE TITLE
[Bug] [r2258] Mix up of chapters in the reader with vertical paging.

### ISSUE THREAD

**Issue by Palloxin** [shosetsuorg/shosetsu#220] opened 2022-06-02 22:00 UTC
**Describe the bug**
Vertical paging.

https://user-images.githubusercontent.com/75091899/171745391-9458cd6a-e1fc-495b-b68b-a0b7870542ae.mp4

**To Reproduce**
1. Open a chapter with vertical paging on
2. Keep clicking in the middle of the screen like in the video

**Expected behavior**
The reader shouldn't mix up chapters with part of previous chapters.

**Screenshots**

**Device information:**
 - OS: Android 8
 - App Version: r2258

**Additional context**

**Comment by Doomsdayrs** [comment] 2022-07-07 04:24
Duplicate of #198

**Closed by Doomsdayrs** 2022-07-07 04:24 UTC
Labels: bug, help wanted, ux, on hold
